channels:
- conda-forge
- defaults
dependencies:
- appnope
- argon2-cffi
- async_generator
- attrs
- backcall
- backports.functools_lru_cache
- backports
- bleach
- boost-cpp
- branca
- brotlipy
- bzip2
- c-ares
- ca-certificates
- cairo
- certifi
- cffi
- cfitsio
- chardet
- click-plugins
- click
- cligj
- cryptography
- curl
- cycler
- decorator
- defusedxml
- descartes
- entrypoints
- expat
- fiona
- folium
- fontconfig
- freetype
- freexl
- gdal
- geopandas
- geos
- geotiff
- gettext
- giflib
- glib
- hdf4
- hdf5
- icu
- idna
- importlib-metadata
- importlib_metadata
- ipykernel
- ipython
- ipython_genutils
- jedi
- jinja2
- joblib
- jpeg
- json-c
- json5
- jsonschema
- jupyter_client
- jupyter_core
- jupyterlab
- jupyterlab_pygments
- jupyterlab_server
- kealib
- kiwisolver
- krb5
- lcms2
- libblas
- libboost
- libcblas
- libcurl
- libcxx
- libdap4
- libedit
- libev
- libffi
- libgdal
- libgfortran5
- libgfortran
- libglib
- libiconv
- libkml
- liblapack
- libnetcdf
- libnghttp2
- libopenblas
- libpng
- libpq
- libsodium
- libspatialindex
- libspatialite
- libssh2
- libtiff
- libwebp-base
- libxml2
- llvm-openmp
- lz4-c
- markupsafe
- matplotlib-base
- mistune
- munch
- nbclient
- nbconvert
- nbformat
- ncurses
- nest-asyncio
- networkx
- notebook
- numpy-base
- numpy
- olefile
- openjpeg
- openssl
- osmnx
- packaging
- pandas
- pandoc
- pandocfilters
- parso
- pcre
- pexpect
- pickleshare
- pillow
- pip
- pixman
- poppler-data
- poppler
- postgresql
- proj
- prometheus_client
- prompt-toolkit
- ptyprocess
- pycparser
- pygments
- pyopenssl
- pyparsing
- pyproj
- pyrsistent
- pysocks
- python-dateutil
- python
- python_abi
- pytz
- pyzmq
- readline
- requests
- rtree
- scikit-learn
- scipy
- send2trash
- setuptools
- shapely
- six
- sqlite
- tbb
- terminado
- testpath
- threadpoolctl
- tiledb
- tk
- tornado
- tqdm
- traitlets
- tzcode
- tzdata
- urllib3
- wcwidth
- webencodings
- wheel
- xerces-c
- xz
- zeromq
- zipp
- zlib
- zstd
name: mainbuilding
